# Generated by Django 3.1.2 on 2020-10-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_Sala', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=5)),
                ('activo', models.BooleanField()),
                ('filas', models.IntegerField()),
                ('asientos', models.IntegerField()),
            ],
        ),
    ]
