# Generated by Django 3.1.2 on 2020-10-12 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminCine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='id_Sala',
            new_name='id_sala',
        ),
    ]
