# Generated by Django 3.1.2 on 2020-10-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCine', '0002_auto_20201012_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('duracion', models.IntegerField()),
                ('descripcion', models.CharField(max_length=160)),
                ('detalle', models.CharField(max_length=500)),
                ('genero', models.CharField(max_length=30)),
                ('clasificacion', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=False)),
                ('fechaComienzo', models.DateField()),
                ('fechaFinalizacion', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='sala',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
    ]
