# Generated by Django 3.1.3 on 2021-01-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCine', '0004_auto_20201014_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='detalle',
            field=models.CharField(max_length=10000),
        ),
    ]
